=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/.elemento.schema.json
{
  "$id": "",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "JSON Schema para os JSONs de definição de cada elemento de diagrama",
  "type": [
    "object"
  ],
  "properties": {
    "classesElemento": {
      "description": "Define quais classes este tipo de elemento deve ter.",
      "type": ["array"],
      "items": {
        "type": "string"
      }
    },
    "recebePontoExtensor": {
      "type": "boolean"
    },
    "recebeSetaConectora": {
      "type": "boolean"
    },
    "valorHtmlInterno": {
      "description": "Define a estrutura interna do HTML deste tipo de elemento",
      "type": ["string"]
    },
    "propriedades": {
      "description": "Define as propriedades deste tipo de elemento que podem ser editadas",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "chaveI18nLabel": {
            "type": "string"
          },
          "classeElemento": {
            "type": "string"
          },
          "nomePropriedade": {
            "type": "string"
          },
          "sufixo": {
            "type": "string"
          },
          "valoresPermitidos": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": [
          "chaveI18nLabel",
          "classeElemento",
          "nomePropriedade",
          "sufixo"
        ]
      }
    }
  },
  "required": [
    "classesElemento",
    "valorHtmlInterno",
    "recebePontoExtensor",
    "recebeSetaConectora",
    "propriedades"
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/nota.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div contenteditable=\"true\" spellcheck=\"true\" class=\"texto\">NOTA</div>",
  "classesElemento": ["elemento-nota"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.text.label",
      "classeElemento": "texto",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/conexao_angulada.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class=\"ponto ponto-norte\"><div class=\"ponto-norte-valor\"></div></div><div class=\"ponto ponto-sul\"><div class=\"ponto-sul-valor\"></div></div>",
  "classesElemento": ["elemento-conexao-angulada"],
  "recebePontoExtensor": false,
  "recebeSetaConectora": false,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.position-north-point.label",
      "classeElemento": "ponto-norte-valor",
      "nomePropriedade": "posicao-ponto-norte",
      "sufixo": "",
      "valoresPermitidos": ["NORTE", "SUL", "LESTE", "OESTE"]
    },
    {
      "chaveI18nLabel": "element.property.position-south-point.label",
      "classeElemento": "ponto-sul-valor",
      "nomePropriedade": "posicao-ponto-sul",
      "sufixo": "",
      "valoresPermitidos": ["NORTE", "SUL", "LESTE", "OESTE"]
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/cardinalidade.json
{
  "$schema": ".elemento.schema.json",
  "classesElemento": [
    "elemento-cardinalidade"
  ],
  "valorHtmlInterno": "<div class=\"tipo\">(0, N)</div>",
  "recebePontoExtensor": false,
  "recebeSetaConectora": false,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.cardinality.label",
      "classeElemento": "tipo",
      "nomePropriedade": "cardinalidade",
      "sufixo": "",
      "valoresPermitidos": ["(0, N)", "(1, N)", "(0, 1)", "(1, 1)"]
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/entidade_relacional.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">tbEntidade</div><div class=\"atributo\" onmouseup=\"callbackAlterarAtributoRelacional(event)\"><span class=\"chave\"><span class=\"desc-chave\"></span></span><span contenteditable=\"true\" spellcheck=\"true\" class=\"texto\">atributo: tipo</span></div><button onclick=\"callbackCriarAtributoRelacional(event)\">+</button>",
  "classesElemento": ["elemento-entidade-relacional"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.name.label",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}
